### ISSUE TITLE
Layer Select

### ISSUE THREAD

**Issue by YaegakiY** [fabriceyhc/mode_nn_debugging#4]
I loaded a vgg19 model and tried Backforward_Layer_Select in layer_selection.py, but it raised an error. 
It seems that it only generated a feature model with a flatten layer. 

> Traceback (most recent call last):
  File "test.py", line 59, in <module>
    x_test, y_test, 10, 0.1)
  File "/root/nas/mode_nn_debugging/py/layer_selection.py", line 133, in Backward_Layer_Select
    feature_model.fit(x_train, y_train, epochs=epochs, verbose=bit)
  File "/root/miniconda3/envs/eai-repair/lib/python3.7/site-packages/keras/engine/training.py", line 1154, in fit
    batch_size=batch_size)
  File "/root/miniconda3/envs/eai-repair/lib/python3.7/site-packages/keras/engine/training.py", line 621, in _standardize_user_data
    exception_prefix='target')
  File "/root/miniconda3/envs/eai-repair/lib/python3.7/site-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected flatten_1 to have shape (3072,) but got array with shape (10,)

**Comment by sastry3009** [comment]
hai I would like to apply this for my data which is of time series. could you please suggest me the modifications to be incorporated. Thank you 

my data is https://github.com/klemenjak/SynD
